# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/James/github/6g-pa-gan-dpd/fpga/rtl/pn_tdnn_100MHz.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps8_0_100M_0/system_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_100M_0 || ORIG_REF_NAME==system_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_my_neural_net_0_0/system_my_neural_net_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_my_neural_net_0_0 || ORIG_REF_NAME==system_my_neural_net_0_0} -quiet] -quiet

# XDC: c:/Users/James/github/6g-pa-gan-dpd/fpga/zcu104_axi_test/zcu104_axi_test.gen/sources_1/bd/system/system_ooc.xdc
